# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install Black
        run: pip install black
        
      - name: Run black --check .
        run: black --check .

      - name: Install isort
        run: pip install isort
      
      - name: Run isort --check-only
        run: isort --check-only
      
      - name: If needed, format files
        run: black . && isort . --profile black

      - name: If needed, commit black and isort changes to the pull request
        if: failure()
        uses: EndBug/add-and-commit@v5.2.0
